//
// Generated file, do not edit! Created by opp_msgtool 6.1 from CustomMessage.msg.
//

#ifndef __CUSTOMMESSAGE_M_H
#define __CUSTOMMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CustomMessage;
/**
 * Class generated from <tt>CustomMessage.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CustomMessage
 * {
 *     //    \@customize(true);  // see the generated C++ header for more info
 *     char M_Header;
 *     string M_Payload;
 *     char M_Trailer;
 *     int M_Type;
 * }
 * </pre>
 */
class CustomMessage : public ::omnetpp::cPacket
{
  protected:
    char M_Header = 0;
    omnetpp::opp_string M_Payload;
    char M_Trailer = 0;
    int M_Type = 0;

  private:
    void copy(const CustomMessage& other);

  protected:
    bool operator==(const CustomMessage&) = delete;

  public:
    CustomMessage(const char *name=nullptr, short kind=0);
    CustomMessage(const CustomMessage& other);
    virtual ~CustomMessage();
    CustomMessage& operator=(const CustomMessage& other);
    virtual CustomMessage *dup() const override {return new CustomMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual char getM_Header() const;
    virtual void setM_Header(char M_Header);

    virtual const char * getM_Payload() const;
    virtual void setM_Payload(const char * M_Payload);

    virtual char getM_Trailer() const;
    virtual void setM_Trailer(char M_Trailer);

    virtual int getM_Type() const;
    virtual void setM_Type(int M_Type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CustomMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CustomMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CustomMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<CustomMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CUSTOMMESSAGE_M_H

